# NUDGE LOGIC SUMMARY — nudge_engine.py
#
# Nudge types (5): context_switch (rapid app switching), energy_drift (frequent
# phone pickups without sustained focus), late_night (late-night work after 22:00),
# meeting_recovery (post back-to-back meetings), focus_mode (user is in focus/DND
# mode). Anchor actions are handled as standalone local notifications on the
# frontend and are no longer part of this engine.
#
# Each nudge message and explanation is generated by claude-3-5-haiku via the
# Anthropic API using a per-type prompt template filled with runtime context
# (switch_count, pickup_count, time). Falls back to hardcoded strings if the
# API call fails.
#
# Delivery gating (all server-side nudges route through deliver_nudge):
#   - micro_mode WHISPER: all engine nudges suppressed (except the Sunday koan)
#   - micro_mode STANDARD: all nudge types allowed
#   - frequency: at most one feed/push nudge per 6 hours
#   - quiet hours: suppress push (still write in-app) during the user's window
#
# Data used: MongoDB collections `nudges` (created/delivered/opened/featured
# state) and `preferences` (micro_mode, quiet_hours_*, tz_offset per user).

from motor.motor_asyncio import AsyncIOMotorDatabase
from datetime import datetime, timedelta
from typing import Dict, Optional
import uuid
import logging
import os
import random
try:
    import anthropic
except ImportError:
    anthropic = None
from models import Nudge, MicroMode, normalize_micro_mode

logger = logging.getLogger(__name__)

NUDGE_TEMPLATES = {
    # context_switch: user has rapidly switched between many apps
    # Example outputs:
    #   "You've been in {switch_count} places at once. Pick one."
    #   "The tabs are open. The question is which one actually matters now."
    "context_switch": {
        "title": "Decide your next step",
        "prompt": (
            "User switched between {switch_count} apps in 30 minutes. "
            "Write one calm observation (10-15 words) about scattered attention — "
            "no advice, no imperatives. Tone: quiet, like a sentence you'd underline in a book."
        )
    },
    # energy_drift: user has picked up their phone many times without focus
    # Example outputs:
    #   "The phone has been picked up {pickup_count} times. Something is pulling at attention."
    #   "{pickup_count} pickups in half an hour. The restlessness is worth noticing."
    "energy_drift": {
        "title": "Time for a reset",
        "prompt": (
            "User picked up their phone {pickup_count} times in 30 minutes without settling. "
            "Write one calm observation (10-15 words) about fragmented attention — "
            "not a suggestion, just a quiet noticing. Tone: understated, not urgent."
        )
    },
    # late_night: user is active on their phone past 22:00
    # Example outputs:
    #   "It's {time}. Most of what feels urgent at this hour isn't."
    #   "The work will look different in the morning. This part can wait."
    "late_night": {
        "title": "Tomorrow can wait",
        "prompt": (
            "User is on their phone at {time}. "
            "Write one calm observation (10-15 words) about late-night activity — "
            "not prescriptive, no 'you should'. Tone: gently matter-of-fact."
        )
    },
    # meeting_recovery: user just finished back-to-back meetings
    # Example outputs:
    #   "Back-to-back meetings done. Two minutes of nothing is not nothing."
    #   "The last meeting just ended. The transition is part of the work."
    "meeting_recovery": {
        "title": "Breathe between meetings",
        "prompt": (
            "User just finished back-to-back meetings. "
            "Write one calm observation (10-15 words) about the value of transition time — "
            "no commands, no urgency. Tone: quiet acknowledgment."
        )
    },
    # focus_mode: user has enabled focus or DND mode
    # Example outputs:
    #   "Focus mode is on. The work you're protecting is worth protecting."
    #   "You cleared the space. That was the harder part."
    "focus_mode": {
        "title": "Focus time",
        "prompt": (
            "User is in focus or do-not-disturb mode. "
            "Write one calm observation (10-15 words) acknowledging their choice — "
            "no motivational language, no pressure. Tone: quiet affirmation."
        )
    },
    # attention_limit: a device-wide Screen Time threshold the user set for
    # their own distracting apps was crossed today (coarse, category-less signal).
    # Example outputs:
    #   "The apps you flagged have had more of today than you meant to give."
    #   "Past the line you drew for yourself. Worth a glance, not a verdict."
    "attention_limit": {
        "title": "A line you drew",
        "prompt": (
            "The apps the user themselves chose to watch crossed {threshold_minutes} minutes today. "
            "Write one calm observation (10-15 words) about attention drifting past a self-set limit — "
            "no advice, no scolding, no numbers. Tone: quiet, like a sentence you'd underline in a book."
        )
    },
}

async def create_nudge(db: AsyncIOMotorDatabase, user_id: str, nudge_type: str, context: Dict):
    """Generate AI nudge content and deliver it through the single gate."""
    try:
        preferences = await db.preferences.find_one({"user_id": user_id})
        # Cheap pre-gate so we don't spend an AI call on a nudge the mode would
        # suppress anyway. deliver_nudge re-applies the authoritative gate.
        micro_mode = normalize_micro_mode(preferences.get("micro_mode") if preferences else None)
        if not should_send_nudge(nudge_type, micro_mode):
            logger.info(f"Skipping nudge type {nudge_type} for mode {micro_mode}")
            return None

        message, explanation = await generate_nudge_content(nudge_type, context, preferences, db, user_id)

        delivered = await deliver_nudge(
            db, user_id,
            {"nudge_type": nudge_type, "message": message, "explanation": explanation},
            channel="both",
        )
        if delivered:
            logger.info(f"Created nudge {delivered['id']} for user {user_id}")
            return Nudge(**delivered)
        return None
    except Exception as e:
        logger.error(f"Error creating nudge: {str(e)}")
        return None

async def generate_nudge_content(
    nudge_type: str,
    context: Dict,
    preferences: Optional[Dict],
    db=None,
    user_id: Optional[str] = None,
) -> tuple:
    """Generate nudge message and explanation using AI"""
    _MODEL = "claude-3-5-haiku-20241022"
    try:
        template = NUDGE_TEMPLATES.get(nudge_type)
        if not template:
            return "Take a moment to refocus", "Based on your recent activity patterns"

        # Prepare prompt with context
        prompt_text = template["prompt"].format(**context)

        # Initialize Anthropic client
        if anthropic is None:
            raise RuntimeError("anthropic library not available; using fallback")
        api_key = os.getenv("ANTHROPIC_API_KEY")
        client = anthropic.AsyncAnthropic(api_key=api_key)
        system_prompt = "You are a subtle behavioral coach. Create brief, calm, professional nudges without clichés or motivational phrases. Be direct and respectful."

        # Generate message
        message_response = await client.messages.create(
            model=_MODEL,
            max_tokens=100,
            system=system_prompt,
            messages=[{"role": "user", "content": prompt_text}]
        )
        message = message_response.content[0].text

        # Generate explanation (why this nudge)
        explanation_prompt = f"In 20-30 words, explain why we're sending this nudge: {message}. Focus on the behavioral pattern observed."
        explanation_response = await client.messages.create(
            model=_MODEL,
            max_tokens=100,
            system=system_prompt,
            messages=[{"role": "user", "content": explanation_prompt}]
        )
        explanation = explanation_response.content[0].text

        # Log combined token usage for both API calls
        if db is not None and user_id is not None:
            input_tokens = (
                message_response.usage.input_tokens
                + explanation_response.usage.input_tokens
            )
            output_tokens = (
                message_response.usage.output_tokens
                + explanation_response.usage.output_tokens
            )
            await db.api_usage.insert_one({
                "user_id": user_id,
                "timestamp": datetime.utcnow(),
                "endpoint": "nudge_generate",
                "model": _MODEL,
                "input_tokens": input_tokens,
                "output_tokens": output_tokens,
                "total_tokens": input_tokens + output_tokens,
                "success": True,
            })

        return message.strip(), explanation.strip()
    except Exception as e:
        logger.error(f"Error generating nudge content: {str(e)}")
        # Log failed call
        if db is not None and user_id is not None:
            try:
                await db.api_usage.insert_one({
                    "user_id": user_id,
                    "timestamp": datetime.utcnow(),
                    "endpoint": "nudge_generate",
                    "model": _MODEL,
                    "input_tokens": 0,
                    "output_tokens": 0,
                    "total_tokens": 0,
                    "success": False,
                })
            except Exception:
                pass
        # Fallback to simple messages
        fallback_messages = {
            "context_switch": ("Pick one thing to focus on", "You've switched between apps frequently"),
            "energy_drift": ("Take a breath, then choose one task", "Multiple phone checks detected"),
            "late_night": ("This can wait until tomorrow", "Late evening work detected"),
            "meeting_recovery": ("A moment to reset before the next thing", "Back-to-back meetings completed"),
        }
        return fallback_messages.get(nudge_type, ("Take a moment", "Based on your patterns"))

def should_send_nudge(nudge_type: str, micro_mode: str) -> bool:
    """Whisper suppresses all engine-generated nudges; Standard allows them."""
    return normalize_micro_mode(micro_mode) != MicroMode.WHISPER


async def _in_quiet_hours(prefs: dict) -> bool:
    """True if the user's local time is within their quiet-hours window.

    Local time uses prefs.tz_offset (minutes east of UTC, last reported by the
    client via the today-card call). Users who have never opened the app have
    no offset, so this falls back to UTC — a v1.0 simplification. Windows that
    cross midnight (e.g. 23:00–07:00) are handled.
    """
    if not prefs.get("quiet_hours_enabled", True):
        return False
    try:
        tz_offset = int(prefs.get("tz_offset", 0) or 0)
        local = datetime.utcnow() + timedelta(minutes=tz_offset)
        cur = local.hour * 60 + local.minute
        sh, sm = map(int, str(prefs.get("quiet_hours_start", "23:00")).split(":"))
        eh, em = map(int, str(prefs.get("quiet_hours_end", "07:00")).split(":"))
        start, end = sh * 60 + sm, eh * 60 + em
        if start == end:
            return False
        if start < end:
            return start <= cur < end
        return cur >= start or cur < end  # crosses midnight
    except Exception:
        return False


async def deliver_nudge(
    db: AsyncIOMotorDatabase,
    user_id: str,
    payload: Dict,
    *,
    channel: str = "both",       # "in_app" | "push" | "both"
    enforce_frequency: bool = True,
    bypass_gates: bool = False,  # the Sunday koan delivers regardless of mode/frequency/quiet-hours
    write: bool = True,          # False for the koan push (content is rendered, not stored)
) -> Optional[Dict]:
    """The single chokepoint for every server-side nudge delivery.

    Gating order: mode (Whisper suppresses) -> frequency (one feed/push nudge
    per 6h, featured cards excluded) -> quiet hours (push suppression only,
    in-app write still happens). Then writes to db.nudges and/or pushes.

    payload keys: nudge_type, message, explanation (opt), trigger_id (opt),
                  featured_at (opt datetime).
    Returns the stored nudge dict, or None if gated out; or {"pushed": bool}
    when write is False.
    """
    prefs = await db.preferences.find_one({"user_id": user_id}) or {}
    micro_mode = normalize_micro_mode(prefs.get("micro_mode"))
    nudge_type = payload.get("nudge_type")

    if not bypass_gates:
        if not should_send_nudge(nudge_type, micro_mode):
            logger.info(f"deliver_nudge: suppressed by mode '{micro_mode}' for {user_id}")
            return None
        if enforce_frequency:
            cutoff = datetime.utcnow() - timedelta(hours=6)
            recent = await db.nudges.find_one({
                "user_id": user_id,
                "created_at": {"$gte": cutoff},
                "featured_at": None,
            })
            if recent:
                logger.info(f"deliver_nudge: frequency-capped for {user_id}")
                return None

    push = channel in ("push", "both")
    if push and not bypass_gates and await _in_quiet_hours(prefs):
        push = False  # quiet hours — write in-app, skip the push

    nudge_dict = None
    if write:
        nudge_style = prefs.get("nudge_style", "silent")
        nudge = Nudge(
            id=str(uuid.uuid4()),
            user_id=user_id,
            nudge_type=nudge_type,
            message=payload["message"],
            explanation=payload.get("explanation", ""),
            delivered=False,
            silent=(nudge_style == "silent"),
            featured_at=payload.get("featured_at"),
        )
        doc = nudge.dict()
        if payload.get("trigger_id"):
            doc["trigger_id"] = payload["trigger_id"]
        await db.nudges.insert_one(doc)
        nudge_dict = nudge.dict()

    if push:
        try:
            from push_notifications import send_nudge_push
            await send_nudge_push(
                db, user_id, payload["message"],
                nudge_id=(nudge_dict["id"] if nudge_dict else ""),
            )
        except Exception as e:
            logger.error(f"deliver_nudge push failed for {user_id}: {e}")

    return nudge_dict if write else {"pushed": push}

async def get_pending_nudges(db: AsyncIOMotorDatabase, user_id: str):
    """Get nudges that haven't been delivered yet.

    Excludes nudges featured on the home "Today" card (featured_at set) so the
    same observation never appears twice. {"featured_at": None} matches both
    null and missing fields in MongoDB, so pre-existing nudges are unaffected.
    """
    nudges = await db.nudges.find({
        "user_id": user_id,
        "delivered": False,
        "featured_at": None,
    }).sort("created_at", -1).to_list(10)

    return [Nudge(**nudge) for nudge in nudges]

async def mark_nudge_delivered(db: AsyncIOMotorDatabase, nudge_id: str):
    """Mark a nudge as delivered"""
    await db.nudges.update_one(
        {"id": nudge_id},
        {"$set": {"delivered": True}}
    )

async def mark_nudge_opened(db: AsyncIOMotorDatabase, nudge_id: str):
    """Mark a nudge as opened"""
    await db.nudges.update_one(
        {"id": nudge_id},
        {"$set": {"opened": True}}
    )

async def check_health_signal_triggers(db, user_id: str, signal: dict) -> Optional[dict]:
    """
    Evaluate a health signal snapshot and generate a nudge if a pattern warrants it.
    Returns a nudge dict or None.
    Each trigger checks a specific condition and maps to a research-grounded principle.
    """
    # NOTE: this function is currently not wired to any route (the health-signal
    # POST uses PatternDetector.get_priority_nudge). Kept and routed through the
    # single gate so that, if re-enabled, it respects mode/frequency/quiet-hours.
    # Get last 7 days of signals for trend detection
    cutoff = (datetime.utcnow() - timedelta(days=7)).strftime("%Y-%m-%d")
    recent = await db.health_signals.find(
        {"user_id": user_id, "date": {"$gte": cutoff}},
        sort=[("date", -1)]
    ).to_list(7)

    nudge_message = None
    nudge_type = None
    explanation = None

    # Trigger 1: First pickup getting earlier or later than baseline
    if signal.get("first_pickup_time") and len(recent) >= 3:
        pickups = [r.get("first_pickup_time") for r in recent if r.get("first_pickup_time")]
        if len(pickups) >= 3:
            # If first pickup is before 7am for 3+ days
            early_pickups = sum(1 for p in pickups if p < "07:00")
            if early_pickups >= 3:
                nudge_message = "Your phone has been the first thing you reach for before the day has even started. The first 30 minutes belong to you."
                nudge_type = "morning_boundary"
                explanation = "First phone pickup detected before 7am for 3 or more consecutive days."

    # Trigger 2: Steps declining over 4+ days
    if not nudge_message and len(recent) >= 4:
        step_counts = [r.get("steps") for r in recent[:4] if r.get("steps")]
        if len(step_counts) == 4 and all(step_counts[i] > step_counts[i+1] for i in range(3)):
            nudge_message = "Movement has been fading this week. It doesn't need to be exercise — a walk after dinner counts more than you think."
            nudge_type = "movement_drift"
            explanation = "Step count has declined for 4 consecutive days."

    # Trigger 3: Sleep timing inconsistent (bedtime varying >90 min)
    if not nudge_message and signal.get("sleep_start") and len(recent) >= 3:
        sleep_starts = [r.get("sleep_start") for r in recent if r.get("sleep_start")]
        if len(sleep_starts) >= 3:
            times = [int(t.replace(":", "")) for t in sleep_starts]
            if max(times) - min(times) > 130:
                nudge_message = "Your sleep schedule has been shifting. Consistency matters more than duration — your body clock notices the drift before you do."
                nudge_type = "sleep_consistency"
                explanation = "Bedtime has varied by more than 90 minutes across recent nights."

    # Trigger 4: Screen time high + steps low on same day
    if not nudge_message:
        if signal.get("total_screen_time_minutes", 0) > 240 and signal.get("steps", 0) < 3000:
            nudge_message = "A long day on screens, a short day on your feet. Even a 10-minute walk resets more than you'd expect."
            nudge_type = "sedentary_screen"
            explanation = "Screen time exceeded 4 hours while step count was below 3000."

    # Trigger 5: Social media disproportionate vs total screen time
    if not nudge_message:
        total = signal.get("total_screen_time_minutes", 0)
        social = signal.get("social_media_minutes", 0)
        if total > 0 and social / total > 0.5 and social > 60:
            nudge_message = "More than half of today's screen time was social media. That's not connection — that's drift."
            nudge_type = "attention_drift"
            explanation = "Social media accounted for over 50% of total screen time."

    if not nudge_message:
        return None

    # Check we haven't sent a nudge of this type recently
    recent_nudge = await db.nudges.find_one({
        "user_id": user_id,
        "nudge_type": nudge_type,
        "created_at": {"$gte": datetime.utcnow() - timedelta(hours=24)}
    })
    if recent_nudge:
        return None

    # Deliver through the single gate (mode/frequency/quiet-hours + write + push).
    delivered = await deliver_nudge(
        db, user_id,
        {"nudge_type": nudge_type, "message": nudge_message, "explanation": explanation},
        channel="both",
    )
    if not delivered:
        return None
    logger.info(f"Created health-signal nudge (type={nudge_type}) for user {user_id}")
    return delivered
