# NUDGE LOGIC SUMMARY — nudge_engine.py
#
# Nudge types (6): context_switch (rapid app switching), energy_drift (frequent
# phone pickups without sustained focus), boundary (late-night work after 22:00),
# meeting_recovery (post back-to-back meetings), anchor_action (daily anchor
# reminder), focus_mode (user is in focus/DND mode).
#
# Each nudge message and explanation is generated by claude-3-5-haiku via the
# Anthropic API using a per-type prompt template filled with runtime context
# (switch_count, pickup_count, time, anchor_action). Falls back to hardcoded
# strings if the API call fails.
#
# Filtering rules:
#   - whisper_mode: skips nudge if any nudge sent in the last 4 hours
#   - micro_mode FOCUS: only focus_mode and anchor_action nudges
#   - micro_mode MEETING: only meeting_recovery and anchor_action nudges
#   - micro_mode WHISPER: anchor_action nudges only (travel or high-pressure periods)
#   - micro_mode STANDARD: all nudge types allowed
#
# Data used: MongoDB collections `nudges` (created/delivered/opened state) and
# `preferences` (whisper_mode, micro_mode, anchor_action per user).

from motor.motor_asyncio import AsyncIOMotorDatabase
from datetime import datetime, timedelta
from typing import Dict, Optional
import uuid
import logging
import os
import random
import anthropic
from models import Nudge, MicroMode

logger = logging.getLogger(__name__)

NUDGE_TEMPLATES = {
    "context_switch": {
        "title": "Decide your next step",
        "prompt": "User has rapidly switched between {switch_count} apps in 30 minutes. Create a calm, subtle nudge (10-15 words) suggesting they choose one focus area."
    },
    "energy_drift": {
        "title": "Time for a reset",
        "prompt": "User has picked up their phone {pickup_count} times in 30 minutes without sustained focus. Create a gentle nudge (10-15 words) suggesting a brief pause or singular focus."
    },
    "boundary": {
        "title": "Tomorrow can wait",
        "prompt": "User is working late at night ({time}). Create a respectful, non-preachy nudge (10-15 words) suggesting to defer non-urgent work."
    },
    "meeting_recovery": {
        "title": "Breathe between meetings",
        "prompt": "User just finished back-to-back meetings. Create a brief reset prompt (10-15 words) to help them transition."
    },
    "anchor_action": {
        "title": "Your anchor action",
        "prompt": "Remind user to do their daily anchor action: '{anchor_action}'. Keep it simple and encouraging (10-15 words)."
    },
    "focus_mode": {
        "title": "Focus time",
        "prompt": "User is in focus mode. Create a supportive nudge (10-15 words) to maintain concentration."
    }
}

async def create_nudge(db: AsyncIOMotorDatabase, user_id: str, nudge_type: str, context: Dict):
    """Create and store a nudge for the user"""
    try:
        # Check if user is in Whisper Mode (fewer nudges)
        preferences = await db.preferences.find_one({"user_id": user_id})
        if preferences and preferences.get("whisper_mode", False):
            # Whisper mode: deliver only 1 in 3 nudges (~70% suppression)
            if random.random() > 0.333:
                logger.info(f"Skipping nudge for user {user_id} in whisper mode (1-in-3 delivery)")
                return None
        
        # Check nudge frequency based on micro-mode
        micro_mode = preferences.get("micro_mode", MicroMode.STANDARD) if preferences else MicroMode.STANDARD
        if not should_send_nudge(nudge_type, micro_mode):
            logger.info(f"Skipping nudge type {nudge_type} for mode {micro_mode}")
            return None
        
        # Generate nudge content using AI
        message, explanation = await generate_nudge_content(nudge_type, context, preferences)
        
        nudge_style = preferences.get("nudge_style", "silent") if preferences else "silent"
        nudge_id = str(uuid.uuid4())
        nudge = Nudge(
            id=nudge_id,
            user_id=user_id,
            nudge_type=nudge_type,
            message=message,
            explanation=explanation,
            delivered=False,
            silent=(nudge_style == "silent"),
        )
        
        await db.nudges.insert_one(nudge.dict())
        logger.info(f"Created nudge {nudge_id} for user {user_id}")
        
        return nudge
    except Exception as e:
        logger.error(f"Error creating nudge: {str(e)}")
        return None

async def generate_nudge_content(nudge_type: str, context: Dict, preferences: Optional[Dict]) -> tuple:
    """Generate nudge message and explanation using AI"""
    try:
        template = NUDGE_TEMPLATES.get(nudge_type)
        if not template:
            return "Take a moment to refocus", "Based on your recent activity patterns"
        
        # Prepare prompt with context
        prompt_text = template["prompt"].format(**context)
        
        # Get anchor action if needed
        if nudge_type == "anchor_action" and preferences:
            context["anchor_action"] = preferences.get("anchor_action", "close one loop")
            prompt_text = template["prompt"].format(**context)
        
        # Initialize Anthropic client
        api_key = os.getenv("ANTHROPIC_API_KEY")
        client = anthropic.AsyncAnthropic(api_key=api_key)
        system_prompt = "You are a subtle behavioral coach. Create brief, calm, professional nudges without clichés or motivational phrases. Be direct and respectful."

        # Generate message
        message_response = await client.messages.create(
            model="claude-3-5-haiku-20241022",
            max_tokens=100,
            system=system_prompt,
            messages=[{"role": "user", "content": prompt_text}]
        )
        message = message_response.content[0].text

        # Generate explanation (why this nudge)
        explanation_prompt = f"In 20-30 words, explain why we're sending this nudge: {message}. Focus on the behavioral pattern observed."
        explanation_response = await client.messages.create(
            model="claude-3-5-haiku-20241022",
            max_tokens=100,
            system=system_prompt,
            messages=[{"role": "user", "content": explanation_prompt}]
        )
        explanation = explanation_response.content[0].text
        
        return message.strip(), explanation.strip()
    except Exception as e:
        logger.error(f"Error generating nudge content: {str(e)}")
        # Fallback to simple messages
        fallback_messages = {
            "context_switch": ("Pick one thing to focus on", "You've switched between apps frequently"),
            "energy_drift": ("Take a breath, then choose one task", "Multiple phone checks detected"),
            "boundary": ("This can wait until tomorrow", "Late evening work detected"),
            "meeting_recovery": ("A moment to reset before the next thing", "Back-to-back meetings completed"),
            "anchor_action": (f"Remember: {context.get('anchor_action', 'your daily anchor')}", "Daily anchor action reminder")
        }
        return fallback_messages.get(nudge_type, ("Take a moment", "Based on your patterns"))

def should_send_nudge(nudge_type: str, micro_mode: str) -> bool:
    """Determine if nudge should be sent based on micro-mode"""
    # Focus mode: anchor reminders only — suppress all other nudges
    if micro_mode == MicroMode.FOCUS:
        return nudge_type == "anchor_action"

    # Meeting mode: prioritize meeting recovery
    if micro_mode == MicroMode.MEETING:
        return nudge_type in ["meeting_recovery", "anchor_action"]

    # Whisper mode: anchor reminders only (for travel or high-pressure periods)
    if micro_mode == MicroMode.WHISPER:
        return nudge_type == "anchor_action"
    
    # Standard mode: all nudges allowed
    return True

async def get_pending_nudges(db: AsyncIOMotorDatabase, user_id: str):
    """Get nudges that haven't been delivered yet"""
    nudges = await db.nudges.find({
        "user_id": user_id,
        "delivered": False
    }).sort("created_at", -1).to_list(10)
    
    return [Nudge(**nudge) for nudge in nudges]

async def mark_nudge_delivered(db: AsyncIOMotorDatabase, nudge_id: str):
    """Mark a nudge as delivered"""
    await db.nudges.update_one(
        {"id": nudge_id},
        {"$set": {"delivered": True}}
    )

async def mark_nudge_opened(db: AsyncIOMotorDatabase, nudge_id: str):
    """Mark a nudge as opened"""
    await db.nudges.update_one(
        {"id": nudge_id},
        {"$set": {"opened": True}}
    )

async def check_health_signal_triggers(db, user_id: str, signal: dict) -> Optional[dict]:
    """
    Evaluate a health signal snapshot and generate a nudge if a pattern warrants it.
    Returns a nudge dict or None.
    Each trigger checks a specific condition and maps to a research-grounded principle.
    """
    prefs = await db.preferences.find_one({"user_id": user_id}) or {}
    micro_mode = prefs.get("micro_mode", "standard")
    if micro_mode == "whisper":
        return None  # whisper mode suppresses health nudges

    # Get last 7 days of signals for trend detection
    cutoff = (datetime.utcnow() - timedelta(days=7)).strftime("%Y-%m-%d")
    recent = await db.health_signals.find(
        {"user_id": user_id, "date": {"$gte": cutoff}},
        sort=[("date", -1)]
    ).to_list(7)

    nudge_message = None
    nudge_type = None
    explanation = None

    # Trigger 1: First pickup getting earlier or later than baseline
    if signal.get("first_pickup_time") and len(recent) >= 3:
        pickups = [r.get("first_pickup_time") for r in recent if r.get("first_pickup_time")]
        if len(pickups) >= 3:
            # If first pickup is before 7am for 3+ days
            early_pickups = sum(1 for p in pickups if p < "07:00")
            if early_pickups >= 3:
                nudge_message = "Your phone has been the first thing you reach for before the day has even started. The first 30 minutes belong to you."
                nudge_type = "morning_boundary"
                explanation = "First phone pickup detected before 7am for 3 or more consecutive days."

    # Trigger 2: Steps declining over 4+ days
    if not nudge_message and len(recent) >= 4:
        step_counts = [r.get("steps") for r in recent[:4] if r.get("steps")]
        if len(step_counts) == 4 and all(step_counts[i] > step_counts[i+1] for i in range(3)):
            nudge_message = "Movement has been fading this week. It doesn't need to be exercise — a walk after dinner counts more than you think."
            nudge_type = "movement_drift"
            explanation = "Step count has declined for 4 consecutive days."

    # Trigger 3: Sleep timing inconsistent (bedtime varying >90 min)
    if not nudge_message and signal.get("sleep_start") and len(recent) >= 3:
        sleep_starts = [r.get("sleep_start") for r in recent if r.get("sleep_start")]
        if len(sleep_starts) >= 3:
            times = [int(t.replace(":", "")) for t in sleep_starts]
            if max(times) - min(times) > 130:
                nudge_message = "Your sleep schedule has been shifting. Consistency matters more than duration — your body clock notices the drift before you do."
                nudge_type = "sleep_consistency"
                explanation = "Bedtime has varied by more than 90 minutes across recent nights."

    # Trigger 4: Screen time high + steps low on same day
    if not nudge_message:
        if signal.get("total_screen_time_minutes", 0) > 240 and signal.get("steps", 0) < 3000:
            nudge_message = "A long day on screens, a short day on your feet. Even a 10-minute walk resets more than you'd expect."
            nudge_type = "sedentary_screen"
            explanation = "Screen time exceeded 4 hours while step count was below 3000."

    # Trigger 5: Social media disproportionate vs total screen time
    if not nudge_message:
        total = signal.get("total_screen_time_minutes", 0)
        social = signal.get("social_media_minutes", 0)
        if total > 0 and social / total > 0.5 and social > 60:
            nudge_message = "More than half of today's screen time was social media. That's not connection — that's drift."
            nudge_type = "attention_drift"
            explanation = "Social media accounted for over 50% of total screen time."

    if not nudge_message:
        return None

    # Check we haven't sent a nudge of this type recently
    recent_nudge = await db.nudges.find_one({
        "user_id": user_id,
        "nudge_type": nudge_type,
        "created_at": {"$gte": datetime.utcnow() - timedelta(hours=24)}
    })
    if recent_nudge:
        return None

    # Create nudge directly with pre-formed content (no AI generation needed)
    nudge_style = prefs.get("nudge_style", "silent")
    nudge_id = str(uuid.uuid4())
    nudge = Nudge(
        id=nudge_id,
        user_id=user_id,
        nudge_type=nudge_type,
        message=nudge_message,
        explanation=explanation,
        delivered=False,
        silent=(nudge_style == "silent"),
    )
    await db.nudges.insert_one(nudge.dict())
    logger.info(f"Created health-signal nudge {nudge_id} (type={nudge_type}) for user {user_id}")
    return nudge.dict()
